### ISSUE TITLE
feature: Hooks for scripts or plugins

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#17]
I'd like to be able to execute code when a report is saved.  Specifically, I'd like to have a PDF generated automatically and uploaded to a DocuShare server.  That task is a bit too specific to be written right into Philadelphia, it should be written as a script or a plug-in that uses a "report_saved" hook.

**Comment by mastbaum** [comment]
this is sort of built into couchdb -- you can specify daemons that get run along with the db server. this is how the post-submit email works. i have a pdf'er in progress, but the platform is there.
