### ISSUE TITLE
feature: Edit existing shift reports

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#18]
Person A starts a report, works on it a bit, saves and logs out.  Person B logs in, opens the report, adds a section, saves and logs out.  Etc.  Maybe this could be done by allowing saving and re-opening of a temporary copy, but once the shift is over and the report is finally saved, it's immutable, other than comments.

**Comment by mastbaum** [comment]
closed by 989fd140d148c5d3a329f96c9198f08e45a81991
