### ISSUE TITLE
feature: History tracking

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#19]
If editing is allowed, Philadelphia should maintain a history of changes made, when and by who for each report.  Wikipedia-style diffs to show what changed between versions.

Though, I really like the idea of immutable shift reports coupled with the ability to save temporary copies while the report is in progress.  History tracking wouldn't be necessary with this system.

**Comment by mastbaum** [comment]
> Though, I really like the idea of immutable shift reports coupled with the ability to save temporary copies while the report is in progress. History tracking wouldn't be necessary with this system.

This is how it works now (0.8+), so closing issue
