### ISSUE TITLE
feature: Required templates or fields

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#21]
Mark some templates (Basic Information, for instance) as required, and start each new report with Required templates already in place.  Mark some fields as required, so if their template is in the report, the report can't be final-saved if any required field is empty.

**Comment by mastbaum** [comment]
fields that can't be deleted in dd430465a5ec37f39af3e6ab6e511009b80b3c80 and templates that show up by default in 672e399454527f27030a1dac9bf5c3d739e8d893 cover this while still allowing the user a lot of flexibility. will add at least a warning re: null required fields when i add the "final save."
