### ISSUE TITLE
interface: Specify plot series from list of existing fields

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#24]
In the plotting app, offer a list of existing fields that can be specified as "x series", "y series", etc

**Comment by mastbaum** [comment]
the text boxes do case-insensitive autocomplete, which i thought was the cleanest way to direct the user toward arbitrary string field names. a list could get unwieldy and hard to sort through.

i could add a hint ("looky! autocompletes!") but think the intuitive user behavior (just start typing what you want) will get them there anyway.

**Comment by bobthebrewer** [comment]
Ah. I admit I didn't try typing in them because I couldn't immediately remember the names of any fields to put in.  This works well, and it doesn't just search from the beginning of the field names either, I can start typing "cat" if that's all I remember, and it immediately narrows down the choices to "The sound a cat makes".
