### ISSUE TITLE
Text in text entry box does not word wrap

### ISSUE THREAD

**Issue by seibert** [mastbaum/philadelphia#42]
Oddly, when viewing a shift report with a text entry box, the text does not appear to wrap to the next line at a word boundary, but rather goes all the way to the edge and splits words in the middle to wrap to the next line.  It makes it kind of hard to read paragraphs.

(Browser: Chrome Version 23.0.1271.26 beta)

**Comment by mastbaum** [comment]
This is a side effect of the contents being wrapped in a `<pre>` tag. I wanted it that way so it would render copy-paste terminal contents, etc., correctly, but it's not so great for normal text. Suppose I could just put text in a fixed-width font, converting linebreaks, HTML content, etc.... Hmm.

**Comment by seibert** [comment]
Ah, looks like there is a CSS property to control this:

https://developer.mozilla.org/en-US/docs/CSS/white-space

**Comment by seibert** [comment]
This might do it:

white-space: pre-wrap;

**Comment by gffs** [comment]
"white-space" controls how white spaces are handled, it's set to "pre-wrap" not to collapse the white spaces, but to allow line breaks. "word-break" is what we may want to change.

At the moment bootstrap.css sets it to "break-all" for "pre". We may prefer "normal" not to break lines between any two letters.

http://www.w3.org/TR/css3-text/#word-break

**Comment by mastbaum** [comment]
closed by #44
