### ISSUE TITLE
breakdown block

### ISSUE THREAD

**Issue by tlatorre-uchicago** [mastbaum/philadelphia#61]
It would be nice to have a block specific for a breakdown which includes things like:
- run number
- crate, card, channel
- base current
- gtid of breakdown event

**Comment by mastbaum** [comment]
@tlatorre-uchicago this already exists, added in December. Are you not seeing it on snopl?

**Comment by tlatorre-uchicago** [comment]
Ah I do see it. Awesome! I was just doing PMTIC repairs and going back through shift reports and didn't see it, but I have been looking at shift reports from the beginning of December.
